/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#FFFFFF",
        "on-primary": "#FFFFFF",
        "outline": "#857375",
        "surface-container-high": "#EDDDCA",
        "on-primary-fixed": "#40101b",
        "surface-container": "#F5EFE9",
        "on-tertiary-fixed": "#252B11",
        "on-error-container": "#6e0a12",
        "surface-tint": "#A25B6C",
        "on-primary-fixed-variant": "#6E4F51",
        "inverse-surface": "#362F31",
        "surface-container-highest": "#E4D3C2",
        "on-secondary-fixed-variant": "#5B4A4B",
        "on-background": "#201A1B",
        "tertiary-container": "#DCE997",
        "surface-container-lowest": "#FFFFFF",
        "surface-bright": "#FFF8F7",
        "surface-container-low": "#FDF2EC",
        "primary-container": "#DABFC3",
        "primary": "#A25B6C",
        "inverse-on-surface": "#FAEEED",
        "surface-variant": "#F4DDDF",
        "on-tertiary-fixed-variant": "#49502D",
        "on-surface-variant": "#534345",
        "tertiary-dim": "#70764D",
        "background": "#FFF8F7",
        "tertiary-fixed-dim": "#C0CD7E",
        "on-secondary-container": "#2B1519",
        "on-secondary-fixed": "#2B1519",
        "on-secondary": "#FFFFFF",
        "on-primary-container": "#400D1B",
        "surface": "#FFF8F7",
        "error-container": "#fa746f",
        "on-surface": "#201A1B",
        "primary-dim": "#8A4456",
        "secondary-dim": "#6E4F51",
        "on-error": "#fff7f6",
        "primary-fixed": "#FFD9Df",
        "tertiary": "#8B8949",
        "error": "#a83836",
        "secondary": "#77575C",
        "secondary-fixed": "#FFD9Df",
        "surface-dim": "#E8D6D8",
        "primary-fixed-dim": "#E2BDC3",
        "secondary-container": "#DABFC3",
        "on-tertiary-container": "#181E05",
        "inverse-primary": "#FFB2BE",
        "outline-variant": "#D8C2C5",
        "error-dim": "#67040d",
        "tertiary-fixed": "#F8FFBD",
        "secondary-fixed-dim": "#E5BDBA",
        "sage-green": "#A25B6C",
        "warm-beige": "#EDDDCA",
      },
      fontFamily: {
        "headline": ["Lora", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
